name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Extensions-SG
      run: dotnet build --no-restore Extensions-SG
    - name: Build Extensions
      run: dotnet build --no-restore Extensions
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
